force-app/main/default/objects/Inspection__c/Inspection__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <label>Inspection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inspection__c/fields/Inspector__c.field-meta.xml
<CustomField>
    <fullName>Inspector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspector</label>
    <referenceTo>Inspector__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inspection__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inspection_Audit__c/Inspection_Audit__c.object-meta.xml
<CustomObject>
    <label>Inspection Audit</label>
    <nameField>
        <label>Inspection Audit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>inspection Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inspection_Audit__c/fields/Inspection__c.field-meta.xml
<CustomField>
    <fullName>Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection</label>
    <referenceTo>Inspection__c</referenceTo>
    <relationshipLabel>inspection Audits</relationshipLabel>
    <relationshipName>inspection_Audits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inspection_Audit__c/fields/New_Inspector__c.field-meta.xml
<CustomField>
    <fullName>New_Inspector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Inspector</label>
    <referenceTo>Inspector__c</referenceTo>
    <relationshipLabel>inspection Audits (New Inspector)</relationshipLabel>
    <relationshipName>inspection_Audits1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inspection_Audit__c/fields/Old_inspector__c.field-meta.xml
<CustomField>
    <fullName>Old_inspector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Old Inspector</label>
    <referenceTo>Inspector__c</referenceTo>
    <relationshipLabel>inspection Audits</relationshipLabel>
    <relationshipName>inspection_Audits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inspector__c/Inspector__c.object-meta.xml
<CustomObject>
    <label>Inspector</label>
    <nameField>
        <label>Inspector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inspector__c/fields/Salesforce_User__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Inspectors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InspectionService.cls
public with sharing class InspectionService {

    public static void beforeInsert(List <Inspection__c> newList){

        for(Inspection__c ins : newList){
            System.debug('Fecha inspección: ' + ins.Inspection_Date__c);
            System.debug('Hoy: ' + Date.today());
            System.debug('Es menor: ' + (ins.Inspection_Date__c < Date.today()));
            if(String.isBlank(ins.Status__c)){
                ins.Status__c = 'Pending';
            }
            if(
                ins.Inspection_Date__c != null &&
                ins.Inspection_Date__c < Date.today()
              ){
                ins.addError('la fecha de inspección no puede ser menor a hoy');
            }
        }
    }

    //Metodo que obtiene los inspectores asociados a los IDs recibidos. 
    private static Map<Id, Inspector__c> getInspector(Set<Id> inspectorIds){
        if(inspectorIds == null || inspectorIds.isEmpty()){
            return new Map<Id, Inspector__c>();
        }
            return new Map<Id, Inspector__c>(
                [
                    SELECT Id, Salesforce_User__c
                    FROM Inspector__c
                    WHERE Id IN :inspectorIds
                ]
            );    
    }

    public static void afterInsert(List<Inspection__c> newList){

        List <Task> tasks = new List <Task>();
       
        Set<Id> inspectorIds = new Set<Id>();

        for( Inspection__c ins : newList){
            if(ins.Inspector__c != null){
                inspectorIds.add(ins.Inspector__c);
            }
        }
       
        Map<Id, Inspector__c> inspectorMap = getInspector(inspectorIds);

        for( Inspection__c ins : newList){

            Inspector__c inspect = inspectorMap.get(ins.Inspector__c);
            if(inspect == null || inspect.Salesforce_User__c == null){
              continue;
            }

            Task t = new Task(
                WhatId = ins.Id,
                OwnerId = inspect.Salesforce_User__c,
                Subject = 'Nueva inspección asignada',
                ActivityDate = ins.Inspection_Date__c
            );
         tasks.add(t);
        }

        if(!tasks.isEmpty()){
            insert tasks;
        }
    }

    public static void afterUpdate(List<Inspection__c> newList, Map<Id, Inspection__c> oldMap){
        
        Set<Id> inspectorIds = new Set<Id>(); // 

        for(Inspection__c ins : newList){
            if(ins.Inspector__c != null){
                inspectorIds.add(ins.Inspector__c);
            }
        }

        Map<Id, Inspector__c> inspectorMap = getInspector(inspectorIds);

        List <Task> tasks = new List <Task>();
       
        List<Inspection_Audit__c> audits = new List<Inspection_Audit__c>();

        for(Inspection__c ins : newList){
           
            Inspection__c oldInsp = oldMap.get(ins.Id);

            if( oldInsp != null && ins.Inspector__c != oldInsp.Inspector__c){
                
                Inspector__c inspect = inspectorMap.get(ins.Inspector__c);
                if(inspect == null ){
                    continue;
                  }

                Task t = new Task(
                    WhatId = ins.Id,
                    OwnerId = inspect.Salesforce_User__c,
                    Subject = 'Cambio de inspector en inspeccion',
                    ActivityDate = ins.Inspection_Date__c
                );
                tasks.add(t);

                Inspection_Audit__c audit = new Inspection_Audit__c(
                    Inspection__c = ins.Id,
                    Old_Inspector__c = oldInsp.Inspector__c,
                    New_Inspector__c = ins.Inspector__c,
                    Change_Date__c = System.now()
                );
                 audits.add(audit);
            }     
        }

        if(!tasks.isEmpty()){
            insert tasks;
        }

        if(!audits.isEmpty()){
            insert audits;
        }
    }

    // public static void createAudit(List<Inspection__c> newList, Map<Id, Inspection__c> oldMap){
    //     List<Inspection_Audit__c> audits = new List<Inspection_Audit__c>();

    //     for(Inspection__c ins : newList){
            
    //         Inspection__c oldIns = oldMap.get(ins.Id);
            
    //         if(oldIns != null && ins.Inspector__c != oldIns.Inspector__c){
                
    //             Inspection_Audit__c audit = new Inspection_Audit__c(
    //                 Inspection__c = ins.Id,
    //                 Old_Inspector__c = oldIns.Inspector__c,
    //                 New_Inspector__c = ins.Inspector__c,
    //                 Change_Date__c = System.now()
    //             );
    //             audits.add(audit);
    //         }
    //     }

    //     if(!audits.isEmpty()){
    //         insert audits;
    //     }
    //  }
}